config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :lines do
  	 post 'decrement', on: :member
  	end

  resources :carts
  root 'store#index'
  #post '/decrement', to: 'lines#decrement'
   


 
resources :products do
get :who_bought, on: :member
end

  resources :products 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/line.rb
class Line < ApplicationRecord
  belongs_to :order ,optional: true
  belongs_to :product,optional: true
  belongs_to :cart


def total_price
	product.price * quantity
end	

   def  d
   	 if self.quantity==1
     self.destroy
     else
     self.quantity -= 1
     end
     self
    end

end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create,:decrement]
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    product = Product.find(params[:product_id]) 
    @line = @cart.add_product(product)


    respond_to do |format|
      if @line.save
        format.html { redirect_to root_url }
        format.js   {@current_item=@line}
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  def decrement
    @line=Line.find(params[:id])
    @line.d
        respond_to do |format|

    if @line.save
      format.html { redirect_to root_url }
      format.js
    end
    end
  end 

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:product_id)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(line) do |f| %>
  <% if line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :cart_id %>
    <%= f.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/_line.html.erb
<% if line==@current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
<td><%= line.quantity %>  &times; </td>
<td><%= line.product.title %></td>
<td class="item_price"><%= number_to_currency(line.total_price) %></td>
<td><%= button_to 'Decrement',decrement_line_path(id:line),remote: true %> </td>
</tr>

app/views/lines/create.js.erb
$('#notice').hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%=j render(@cart) %>");

$('#current_item').css({'background-color':'#88ff88'}).
  animate({'background-color':'#114411'},1000);

app/views/lines/decrement.js.erb
$('#cart').html("<%=j render(@cart) %>");

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lines</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.product %></td>
        <td><%= line.cart %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form', line: @line %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line.cart %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>